import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import { Suspense } from "react";
import { ThemeProvider } from "@/components/ThemeProvider";

const dmSans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm-sans"
})
export const metadata: Metadata = {
  title: "Learning Mangment",
  description: "Generated by Omar Elnady",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${dmSans.className}  antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange={false}
          storageKey="lms-theme"
        >
          <ClerkProvider
            publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
            appearance={{
              elements: {
                footer: {
                  "& > div > div:nth-child(1)": {
                    background: "#FFFFFF",
                    display: "none"
                  },
                },
              }
            }
            } >
            <Providers>
              <Suspense fallback={null}>
                <div className="mx-auto w-full h-full justify-center items-center">
                  {children}
                </div>
              </Suspense>
              <Toaster richColors closeButton />
            </Providers>
          </ClerkProvider>
        </ThemeProvider>
      </body>
    </html >
  );
}
