import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";

const dmSans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm-sans"
})
export const metadata: Metadata = {
  title: "Learning Mangment",
  description: "Generated by Omar Elnady",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.className}  antialiased`}
      >
        <ClerkProvider appearance={{
          elements: {
            footer: {
              "& > div > div:nth-child(1)": {
                background: "#FFFFFF",
                display: "none"
              },
            },
          }
        }
        } >
          <Providers>
            <div className="root-layout">
              {children}
            </div>
            <Toaster richColors closeButton />
          </Providers>
        </ClerkProvider>
      </body>
    </html >
  );
}
